package com.application.canopy.model;

public enum AchievementId {
    GERMOGLIO_DI_DISCIPLINA,
    RADICI_SALDE,
    ALBERO_GIOVANE,
    QUERCIA_DELLA_COSTANZA,
    MATTINIERO,
    NOTTURNO_SILENZIOSO,
    SETTIMANA_VERDE,
    FOGLIA_NUOVA,
    MARATONETA_DEL_FOCUS,
    RINASCITA,
    SOLE_DI_MEZZOGIORNO,
    ALBERO_ANTICO,
    FORESTA_NOTTURNA
}